name: Build static site

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install and build site
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build site
        run: pnpm build
      - uses: thedoctor0/zip-release@0.7.6
        with:
          type: zip
          path: dist
          filename: release.zip
      - name: Get latest commit SHA
        run: git rev-parse HEAD > checksum.txt
      - uses: ncipollo/release-action@v1
        with:
          tag: latest
          makeLatest: true
          artifacts: release.zip,checksum.txt
          body: "Latest static site build of landing page"
          allowUpdates: true
          removeArtifacts: true
